[buildPlans.Iosevka]
family = "Iosevka"
spacing = "term"
serifs = "slab"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Iosevka.variants]
  inherits = "ss09"

    [buildPlans.Iosevka.variants.design]
    one = "base"
    two = "curly-neck-serifed"
    zero = "oval-slashed"
    capital-q = "closed-swash"
    g = "single-storey-serifed"
    i = "serifed-semi-tailed"
    punctuation-dot = "round"
    braille-dot = "round"
    asterisk = "penta-low"
    paren = "large-contour"
    brace = "straight"
    guillemet = "curly"
    percent = "rings-continuous-slash"
    lig-neq = "slightly-slanted-dotted"

    [buildPlans.Iosevka.variants.italic]
    one = "base"
    two = "curly-neck-serifed"
    zero = "oval-slashed"
    capital-q = "closed-swash"
    f = "flat-hook-tailed"
    g = "single-storey-serifed"
    i = "serifed-semi-tailed"
    punctuation-dot = "round"
    asterisk = "penta-low"
    paren = "large-contour"
    brace = "straight"
    guillemet = "curly"
    percent = "rings-continuous-slash"

  [buildPlans.Iosevka.ligations]
  inherits = "dlig"

[buildPlans.Iosevka.widths.Normal]
shape = 500
menu = 5
css = "normal"
