[buildPlans.Iosevka]
family = "Iosevka"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Iosevka.variants]
  inherits = "ss09"

    [buildPlans.Iosevka.variants.design]
    one = "base"
    two = "curly-neck-serifless"
    four = "semi-open-serifless"
    five = "upright-flat-serifless"
    zero = "oval-slashed"
    capital-d = "standard-serifless"
    capital-q = "closed-swash"
    i = "serifed-semi-tailed"
    r = "hookless-top-serifed"
    punctuation-dot = "round"
    asterisk = "penta-low"
    paren = "large-contour"
    brace = "straight"
    guillemet = "curly"
    percent = "rings-continuous-slash"

  [buildPlans.Iosevka.ligations]
  inherits = "dlig"

[buildPlans.Iosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iosevka.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.Iosevka.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Iosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
