# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1

CABAL_CORE_LIB_GHC_PV="9.6.6"
CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Platform-agnostic library for filesystem operations"
HOMEPAGE="https://hackage.haskell.org/package/directory"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-lang/ghc-9.6.6:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.10.1.0
"
